import streamlit as st
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(
    page_title="ART-Tox Sentinel",
    page_icon="🏥",
    layout="wide"
)

# Load data
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
df = pd.read_csv(os.path.join(BASE_DIR, 'naija_art_clinic_clean.csv'))

# ── Derive combined risk flag ──────────────────────────────────────────────────
df['combined_risk_flag'] = (
    (df['renal_risk_flag'] == 1) & (df['cardio_risk_flag'] == 1)
).astype(int)

# ── Title & intro ──────────────────────────────────────────────────────────────
st.title("🏥 ART-Tox Sentinel")
st.markdown(
    "A prototype clinical decision-support dashboard simulating organ toxicity "
    "surveillance for HIV patients on first-line antiretroviral therapy (ART) in "
    "Nigerian clinic settings. Designed for use by clinic data officers and HIV "
    "program researchers evaluating regimen-level toxicity patterns."
)

# ── Synthetic data banner ──────────────────────────────────────────────────────
st.warning(
    "⚠️ **Simulation only.** All data in this dashboard is fully synthetic, "
    "generated to reflect Nigerian ART clinic parameters (WHO Nigeria 2025 guidelines, "
    "CKD-EPI renal equations). This tool is not validated for clinical use and should "
    "not inform real patient management decisions."
)

st.markdown("---")

# ── Workflow indicator ─────────────────────────────────────────────────────────
st.markdown("#### How This Dashboard Works")
st.markdown(
    "This tool follows a structured pipeline. Each stage feeds into the next:"
)
col_w1, col_w2, col_w3, col_w4 = st.columns(4)
with col_w1:
    st.info("**① INPUT**\n\nSynthetic patient records: demographics, ART regimen, routine lab values (creatinine, eGFR, BP, BMI, QTc)")
with col_w2:
    st.info("**② PROCESSING**\n\nRule-based risk logic applied to each patient record using WHO-aligned clinical thresholds")
with col_w3:
    st.info("**③ RISK OUTPUT**\n\nPatients flagged as: Renal Risk, CV Risk, Severe QTc Risk, or Combined Risk (renal + CV)")
with col_w4:
    st.info("**④ INTERPRETATION**\n\nRegimen-level summaries and monitoring recommendations generated from flagged cohort")

st.markdown("---")

# ── Risk logic transparency ────────────────────────────────────────────────────
st.markdown("#### Risk Flag Logic (Plain English)")
st.markdown("Every flag in this dashboard is generated by a simple, explainable rule. No black-box models.")

col_r1, col_r2, col_r3, col_r4 = st.columns(4)
with col_r1:
    st.error(
        "🔴 **Renal Risk**\n\n"
        "Creatinine **>1.3 mg/dL**\n\n"
        "*or* eGFR **<60 mL/min**\n\n"
        "*or* Urine protein **>30 mg/dL**\n\n"
        "→ Possible kidney stress from TDF accumulation"
    )
with col_r2:
    st.error(
        "🔴 **CV Risk**\n\n"
        "Systolic BP **>140 mmHg**\n\n"
        "*or* Diastolic BP **>90 mmHg**\n\n"
        "*or* Fasting glucose **100–125 mg/dL**\n\n"
        "*or* BMI **>30**\n\n"
        "→ Metabolic syndrome markers, linked to DTG weight gain"
    )
with col_r3:
    st.error(
        "🔴 **Severe QTc Risk**\n\n"
        "QTc **>450 ms** (male)\n\n"
        "QTc **>470 ms** (female)\n\n"
        "→ Cardiac conduction risk, linked to high BMI / metabolic syndrome"
    )
with col_r4:
    st.error(
        "🔴 **Combined Risk**\n\n"
        "Renal Risk flag **AND** CV Risk flag both active\n\n"
        "→ Highest-priority patients: dual organ stress requiring urgent regimen review"
    )

st.caption("Flags marked **−1** indicate missing lab data; risk status is indeterminate for those patients.")

st.markdown("---")

# ── Sidebar filters ────────────────────────────────────────────────────────────
st.sidebar.header("Filters")
regimen_filter = st.sidebar.multiselect(
    "Select ART Regimen:",
    options=df['art_regimen'].unique(),
    default=df['art_regimen'].unique(),
    placeholder="All selected"
)
sex_filter = st.sidebar.multiselect(
    "Select Sex:",
    options=df['sex'].unique(),
    default=df['sex'].unique(),
    placeholder="All selected"
)

df_filtered = df[
    (df['art_regimen'].isin(regimen_filter)) &
    (df['sex'].isin(sex_filter))
]

if df_filtered.empty:
    st.error("No patients match the selected filters. Adjust the sidebar selections.")
    st.stop()

# ── Key metrics ────────────────────────────────────────────────────────────────
st.subheader("Cohort Overview")
col1, col2, col3, col4, col5 = st.columns(5)
with col1:
    st.metric("Patients in View", len(df_filtered))
with col2:
    renal_pct = (df_filtered['renal_risk_flag'] == 1).mean() * 100
    st.metric("Renal Risk", f"{renal_pct:.1f}%",
              help="Creatinine >1.3 mg/dL, eGFR <60 mL/min, or proteinuria >30 mg/dL")
with col3:
    cv_pct = (df_filtered['cardio_risk_flag'] == 1).mean() * 100
    st.metric("CV Risk", f"{cv_pct:.1f}%",
              help="SBP >140 mmHg, DBP >90 mmHg, fasting glucose 100–125 mg/dL, or BMI >30")
with col4:
    qtc_pct = (df_filtered['severe_qtc_flag'] == 1).mean() * 100
    st.metric("Severe QTc Risk", f"{qtc_pct:.1f}%",
              help="QTc >450 ms (male) or >470 ms (female)")
with col5:
    combined_pct = (df_filtered['combined_risk_flag'] == 1).mean() * 100
    st.metric("Combined Risk", f"{combined_pct:.1f}%",
              help="Patients flagged for both renal AND cardiovascular risk simultaneously")

st.markdown("---")

# ── Risk distribution plots ────────────────────────────────────────────────────
st.subheader("Risk Distribution by ART Regimen")
fig, ax = plt.subplots(1, 2, figsize=(12, 5))

sns.countplot(data=df_filtered, x='art_regimen', hue='renal_risk_flag', ax=ax[0],
              palette={0: '#4C9BE8', 1: '#E84C4C', -1: '#AAAAAA'})
ax[0].set_title('Renal Risk Flag by Regimen')
ax[0].set_xlabel('ART Regimen')
ax[0].set_ylabel('Patient Count')
handles, _ = ax[0].get_legend_handles_labels()
ax[0].legend(handles, ['No Risk (0)', 'At Risk (1)', 'Unknown (-1)'], title='Renal Risk')

sns.countplot(data=df_filtered, x='art_regimen', hue='cardio_risk_flag', ax=ax[1],
              palette={0: '#4C9BE8', 1: '#E84C4C', -1: '#AAAAAA'})
ax[1].set_title('CV Risk Flag by Regimen')
ax[1].set_xlabel('ART Regimen')
ax[1].set_ylabel('Patient Count')
handles, _ = ax[1].get_legend_handles_labels()
ax[1].legend(handles, ['No Risk (0)', 'At Risk (1)', 'Unknown (-1)'], title='CV Risk')

plt.tight_layout()
st.pyplot(fig)
plt.close()

st.markdown("---")

# ── Filter-responsive clinical interpretation ──────────────────────────────────
st.subheader("Clinical Interpretation")

active_regimens = df_filtered['art_regimen'].unique().tolist()
tdf_regimens = [r for r in active_regimens if 'TDF' in r]
dtg_regimens = [r for r in active_regimens if 'DTG' in r]

col1, col2 = st.columns(2)

with col1:
    if tdf_regimens:
        st.info(
            "**Renal Risk Pattern — TDF-containing regimens:**\n\n"
            f"Active in view: {', '.join(tdf_regimens)}\n\n"
            "TDF accumulates in proximal tubular cells via OAT1/OAT3 transporters, "
            "causing mitochondrial dysfunction and progressive eGFR decline. "
            "Monitor eGFR every 3 months. Switch to ABC if eGFR falls below 60 mL/min "
            "or significant proteinuria develops."
        )
    else:
        st.success(
            "**Renal Risk Pattern:**\n\n"
            "No TDF-containing regimens in current view. "
            "Renal toxicity risk from TDF is not applicable to the selected cohort."
        )

with col2:
    if dtg_regimens:
        st.warning(
            "**CV Risk Pattern — DTG-containing regimens:**\n\n"
            f"Active in view: {', '.join(dtg_regimens)}\n\n"
            "DTG is associated with weight gain and insulin resistance, contributing to "
            "dyslipidemia and elevated cardiometabolic risk. "
            "Lifestyle counseling at every visit is recommended. "
            "Consider fasting lipid panel every 6 months for patients on DTG-based regimens."
        )
    else:
        st.success(
            "**CV Risk Pattern:**\n\n"
            "No DTG-containing regimens in current view. "
            "DTG-associated cardiometabolic risk is not applicable to the selected cohort."
        )

st.markdown("---")

# ── Clinical marker distributions ─────────────────────────────────────────────
st.subheader("Clinical Marker Distributions")
col1, col2 = st.columns(2)

with col1:
    fig2, ax2 = plt.subplots(figsize=(6, 4))
    sns.boxplot(data=df_filtered, x='art_regimen', y='egfr_ml_min', ax=ax2)
    ax2.set_title('eGFR Distribution by Regimen')
    ax2.set_ylabel('eGFR (mL/min)')
    ax2.set_xlabel('ART Regimen')
    ax2.axhline(60, color='red', linestyle='--', label='CKD threshold (60 mL/min)')
    ax2.legend()
    plt.xticks(rotation=15)
    st.pyplot(fig2)
    plt.close()

with col2:
    fig3, ax3 = plt.subplots(figsize=(6, 4))
    sns.boxplot(data=df_filtered, x='art_regimen', y='bmi', ax=ax3)
    ax3.set_title('BMI Distribution by Regimen')
    ax3.set_ylabel('BMI (kg/m²)')
    ax3.set_xlabel('ART Regimen')
    ax3.axhline(30, color='red', linestyle='--', label='Obesity threshold (BMI 30)')
    ax3.legend()
    plt.xticks(rotation=15)
    st.pyplot(fig3)
    plt.close()

st.markdown("---")

# ── Clinical Decision Support table ───────────────────────────────────────────
st.subheader("Clinical Decision Support")
st.markdown(
    "The table below summarises risk flag rates and median eGFR per regimen "
    "for the current filtered cohort. Risk flag values represent the **proportion "
    "of patients flagged as at-risk** (0 = no patient at risk, 1 = all patients at risk). "
    "Negative values (−1) indicate missing lab data."
)

regimen_risks = df_filtered.groupby('art_regimen').agg(
    renal_risk_proportion=('renal_risk_flag', lambda x: (x == 1).mean()),
    cardio_risk_proportion=('cardio_risk_flag', lambda x: (x == 1).mean()),
    severe_qtc_proportion=('severe_qtc_flag', lambda x: (x == 1).mean()),
    combined_risk_proportion=('combined_risk_flag', lambda x: (x == 1).mean()),
    median_egfr_ml_min=('egfr_ml_min', 'median')
).round(3)

regimen_risks.columns = [
    'Renal Risk (proportion)',
    'CV Risk (proportion)',
    'Severe QTc Risk (proportion)',
    'Combined Risk (proportion)',
    'Median eGFR (mL/min)'
]

st.dataframe(regimen_risks, use_container_width=True)

st.markdown("### Regimen-Specific Monitoring Recommendations")

recs = {
    'TDF/3TC/EFV': (
        "**Renal monitoring priority.** Obtain baseline eGFR before initiation. "
        "Recheck every 3 months. Switch to ABC/3TC if eGFR falls below 60 mL/min "
        "or significant proteinuria is confirmed."
    ),
    'TDF/3TC/DTG': (
        "**Highest combined renal and CV risk in this cohort.** Monitor eGFR, weight, "
        "and fasting lipids every 3 months. Consider DTG-sparing regimen if metabolic "
        "complications (obesity, dyslipidemia, impaired fasting glucose) arise."
    ),
    'ABC/3TC/DTG': (
        "**Preferred for patients with pre-existing CKD or renal risk factors.** "
        "Lower renal toxicity profile versus TDF-based regimens. Screen for HLA-B*5701 "
        "before initiation if status is unknown. Monitor weight and cardiometabolic "
        "markers given DTG component."
    ),
}

for regimen, rec in recs.items():
    if regimen in regimen_risks.index:
        st.info(f"**{regimen}:** {rec}")

st.markdown("---")

# ── Patient-level risk table ───────────────────────────────────────────────────
st.subheader("High-Risk Patient Surveillance List")
st.markdown(
    "Patients flagged for **both renal and cardiovascular risk simultaneously**. "
    "This combined-risk cohort represents the highest-priority group for clinical "
    "review and potential regimen adjustment. Sorted by eGFR ascending (lowest kidney "
    "function first)."
)

high_risk_cols = [
    'patient_id', 'age', 'sex', 'art_regimen',
    'egfr_ml_min', 'creatinine_mg_dl', 'systolic_bp',
    'bmi', 'fasting_glucose_mg_dl',
    'renal_risk_flag', 'cardio_risk_flag', 'combined_risk_flag'
]

high_risk_df = df_filtered[df_filtered['combined_risk_flag'] == 1][high_risk_cols].copy()
high_risk_df = high_risk_df.sort_values('egfr_ml_min', ascending=True).reset_index(drop=True)

high_risk_df.columns = [
    'Patient ID', 'Age', 'Sex', 'ART Regimen',
    'eGFR (mL/min)', 'Creatinine (mg/dL)', 'Systolic BP (mmHg)',
    'BMI (kg/m²)', 'Fasting Glucose (mg/dL)',
    'Renal Risk', 'CV Risk', 'Combined Risk'
]

st.markdown(f"**{len(high_risk_df)} patients** flagged for combined renal and CV risk in current view.")

if len(high_risk_df) > 0:
    st.dataframe(
        high_risk_df.style.map(
            lambda v: 'background-color: #5c1a1a; color: white;' if v == 1 else '',
            subset=['Renal Risk', 'CV Risk', 'Combined Risk']
        ),
        use_container_width=True,
        height=350
    )
else:
    st.success("No patients with combined renal and CV risk in the current filtered view.")

st.markdown("---")

# ── Raw data toggle ────────────────────────────────────────────────────────────
if st.checkbox("Show Full Raw Data"):
    st.dataframe(df_filtered)
    st.caption(f"Displaying {len(df_filtered)} synthetic patient records.")

st.markdown("---")

# ── About / Methods ────────────────────────────────────────────────────────────
with st.expander("About This Tool / Methods"):
    st.markdown("""
### What is ART-Tox Sentinel?

ART-Tox Sentinel is a prototype health informatics dashboard built to simulate
automated toxicity surveillance for HIV patients on first-line antiretroviral therapy
in Nigerian public sector clinic settings. It demonstrates how routine laboratory
data such as renal markers, cardiometabolic indicators and ECG-derived QTc intervals 
can be structured into a risk-flagging pipeline to support clinical monitoring workflows.

---

### Data

All patient data used in this dashboard is **fully synthetic**. It was generated
programmatically to reflect realistic Nigerian ART clinic demographics and clinical
distributions, based on the following sources:

- WHO Nigeria ART guidelines (2025 update)
- Nigerian HIV/AIDS Indicator and Impact Survey (NAIIS) demographic proportions
- Published Nigerian cohort data on ART-associated nephrotoxicity and weight gain

The synthetic cohort (n = 500) includes mechanism-based missing data to simulate
rural clinic data quality gaps, including missing BP readings, creatinine values,
and ECG results.

---

### Risk Flag Definitions

| Flag | Threshold |
|------|-----------|
| Renal Risk | Creatinine >1.3 mg/dL, OR eGFR <60 mL/min, OR urine protein >30 mg/dL |
| CV Risk | SBP >140 mmHg, OR DBP >90 mmHg, OR fasting glucose 100–125 mg/dL, OR BMI >30 |
| Severe QTc | QTc >450 ms (male), QTc >470 ms (female) |
| Combined Risk | Renal Risk AND CV Risk both flagged simultaneously |
| Unknown (−1) | Relevant lab values missing; risk status indeterminate |

eGFR calculated using the **CKD-EPI 2009 equation** (race-free formulation),
incorporating age, sex, and serum creatinine.

---

### Limitations

- All findings are derived from synthetic data and carry no clinical validity
- Risk thresholds are rule-based; no machine learning or statistical modelling is applied
- The tool has not been tested in or validated against any real clinical environment
- Missing data handling is limited to high-risk patient imputation only
- This prototype does not account for drug duration, adherence, or comorbidity burden

---

### Intended Use

This tool is intended as a **proof-of-concept** for researchers, health informaticians,
and digital health practitioners interested in ART toxicity monitoring infrastructure
for low-resource settings. It is not suitable for clinical deployment in its current form.

---

*Built with Python, Streamlit, pandas, matplotlib, and seaborn.*
*ART-Tox Sentinel v0.1 — Open source prototype.*
    """)

st.markdown("---")
st.caption(
    "ART-Tox Sentinel v0.1 | Prototype — Simulation Only | "
    "Synthetic data modeled on Nigerian ART clinic parameters. "
    "Not validated for clinical deployment."
)
